services:
  - type: web
    name: jetx-predictor-dashboard
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CHROME_BIN
        value: /app/.apt/usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /app/.chromedriver/bin/chromedriver
